language: csharp
solution: ./src/Localidade/Localidade.sln
install:
  - nuget restore ./src/Localidade/Localidade.sln
  - sudo apt-get install nunit-console  
script:
  - msbuild  /p:Configuration=Debug ./src/Localidade/Localidade.sln
  - nunit-console Dominio.Localidade.Tests.dll
 
